[package]
name = "polars-tzf"
version = "0.1.0"
edition = "2021"

[lib]
name = "polars_tzf"
crate-type = ["cdylib"]

[dependencies]
polars = { version = "*", default-features = false }
pyo3 = { version = "*", features = ["extension-module", "abi3-py310"] }
pyo3-polars = { version = "*", features = ["derive"] }
tzf-rs = "1"
serde = { version = "*", features = ["derive"] }

[profile.release]
lto = "thin"
